Added DOC to Markdown Converter Function - Issue #23
microsoft/markitdown pull request #37
Opened 2024-12-15 15:48 UTC by aviral-bhardwaj

### Added DOC to Markdown Converter Function

1. This commit introduces a new DocConverter class that extends the HtmlConverter class to handle the conversion of DOC files to Markdown format. The key features of this implementation are:
2. File Type Validation: The converter checks if the file extension is ".doc" before proceeding with the conversion.
3. Conversion Process:
4. The function uses the mammoth library to convert the DOC file to HTML.
5. It then utilizes the inherited _convert method to transform the HTML content into Markdown.

Issue URL- [This is Issue URL](https://github.com/microsoft/markitdown/issues/23) 

Closed Previous same PR due to the PyCharm Indentation Errors

2024-12-15 15:49 UTC, aviral-bhardwaj commented
@StanFromIreland Please review this due to pycharm i was getting indentation error in my last PR

2024-12-15 16:00 UTC, realrajaryan commented
should add test(s)

2024-12-15 16:05 UTC, aviral-bhardwaj commented
adding but having problem to run that

2024-12-15 16:19 UTC, aviral-bhardwaj commented
added test cases and it is passed

2024-12-16 09:15 UTC, aviral-bhardwaj commented
can anyone please help me here @gagb , I am not able to run tests and pre-commits

2024-12-16 09:16 UTC, aviral-bhardwaj commented
it is showing this in my pycharm 


================== 2 passed, 1 skipped, 3 warnings in 26.27s ===================
PASSED                        [ 33%]PASSED                         [ 66%]SKIPPED (do not run if
exiftool is not installed)                                               [100%]
Skipped: do not run if exiftool is not installed

2024-12-16 14:01 UTC, l-lumin requested changes

2024-12-16 14:10 UTC, aviral-bhardwaj commented on src/markitdown/_markitdown.py
> +               """
fixed

2024-12-16 15:08 UTC, l-lumin commented on src/markitdown/_markitdown.py
> +               """
can you check again? It still misaligned

2024-12-16 15:17 UTC, aviral-bhardwaj commented
fixed according to review as the Args are creating issue in pychram so removed them according to all other functions

2024-12-16 15:48 UTC, l-lumin approved these changes
LGTM. Sorry, I'm just a random person passing by, so I can't magically approve this!

2024-12-16 16:00 UTC, aviral-bhardwaj commented
@realrajaryan sir please can you help me to move forward

2024-12-16 21:18 UTC, gagb commented
> can anyone please help me here @gagb , I am not able to run tests and pre-commits 

You can run precommit via 'pre-commit run --all-files' and then update the PR

2024-12-16 23:23 UTC, gagb commented
Another PR introduced conflicts, can you please resolve?

2024-12-17 13:29 UTC, aviral-bhardwaj commented
@gagb sir please review this , I have updated the test code ,help me to merge this

2024-12-18 00:22 UTC, gagb commented
> @gagb sir please review this , I have updated the test code ,help me to merge this

Thanks, will get it merged soon. Appreciate your contributions.

2024-12-18 02:59 UTC, tungsten106 commented
@aviral-bhardwaj I wonder how you used mammoth to convert .doc file to html? I have tried on my own .doc file, it riased error `OSError: Could not find main document part. Are you sure this is a valid .docx file?`

2024-12-18 04:25 UTC, realrajaryan requested changes
Mammoth does not support converting doc file format, need to find an alternative.

2024-12-18 04:25 UTC, realrajaryan commented on src/markitdown/_markitdown.py
> +            result = mammoth.convert_to_html(doc_file)
mammoth does not seem to support **.doc** files

2024-12-18 04:25 UTC, realrajaryan commented on tests/test_files/test.doc
Looks like this is not a proper doc file. If you just renamed test.docx to test.doc, it does not effectively convert it into a .doc file, it merely changes the file extension while retaining the docx file format. This is why your test passes when it shouldn’t, as mammoth does not support doc files.

2024-12-18 05:38 UTC, aviral-bhardwaj commented on tests/test_files/test.doc
ok checking , will update

2024-12-18 07:41 UTC, aviral-bhardwaj commented
added new doc file this is running in my local without any issue 

<img width="900" alt="Screenshot 2024-12-18 at 1 11 14 PM" src="https://github.com/user-attachments/assets/9c713441-c0c8-4880-b098-b7876f4532e5" />

2024-12-18 07:59 UTC, realrajaryan requested changes

2024-12-18 07:59 UTC, realrajaryan commented on tests/test_files/test.doc
This is still not a valid doc file. The MIME type for this file is **application/octet-stream**, but for a doc file it’s supposed to be **application/msword**.

2024-12-18 08:21 UTC, aviral-bhardwaj commented
added new doc file attaching its info snapshot also 

<img width="416" alt="Screenshot 2024-12-18 at 1 49 03 PM" src="https://github.com/user-attachments/assets/67738839-0411-4736-8594-38b36f90bbc3" />

2024-12-18 09:41 UTC, aviral-bhardwaj commented
yes doing more research on this , will update soon

2024-12-20 08:26 UTC, aviral-bhardwaj commented
this PR can be closed as this feature is completed from this PR https://github.com/microsoft/markitdown/pull/153

2024-12-20 19:01 UTC, closed without merging